dist: trusty
language: node_js
sudo: false
node_js:
  - "10"
addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm install
  - npm run sandbox
script:
  - npm start
  - sleep 5
  - npm test